export const slides = [
  {
    id: 1,
    title: "Авто в лизинг для физических лиц",
    text: "Получите машину за 5 дней",
    buttonText: "Оставить заявку",
    isDisabled: false,
    isLoading: false,
  },
  {
    id: 2,
    title: "Авто лизинг для юр лиц",
    text: "Получите машину за 7 дней",
    buttonText: "Оставить заявку 2",
    isDisabled: false,
    isLoading: true,
  },
  {
    id: 3,
    title: "Авто лизинг для лиц нормер 3",
    text: "Получите машину",
    buttonText: "Оставить заявку 3",
    isDisabled: false,
    isLoading: false,
  },
  {
    id: 4,
    title: "Авто лизинг  для лиц нормер 4",
    text: "Получите еще одну машину",
    buttonText: "Оставить заявку 4",
    isDisabled: false,
    isLoading: false,
  },
  {
    id: 5,
    title: "Авто лизинг для лиц нормер 5",
    text: "Получите 5 машин",
    buttonText: "Оставить заявку 5",
    isDisabled: true,
    isLoading: false,
  },
];
